In [1]:
#Andreas Constantinou
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from collections import Counter
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from scipy.stats import spearmanr
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.datasets import load_iris
from sklearn import tree
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import datasets

In [2]:
df = pd.read_csv("diabetes_012.csv")
df['Diabetes_012'].replace({2.0:1.0}, inplace = True)

In [3]:
Diabetes = df['Diabetes_012']
column_array = ['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']
all_correlations = []
for i in range (len(column_array)):
    current_index = df[column_array[i]]
    spearmanr_coefficient, p_value = spearmanr(Diabetes, current_index)
    all_correlations.append([column_array[i], spearmanr_coefficient])

all_correlations.sort(key = lambda all_correlations : all_correlations[1], reverse = True)
for i in range(len(all_correlations)):
    print("For " + str(all_correlations[i][0]) + ', correlation with diabetes: ' + str(all_correlations[i][1]))

For GenHlth, correlation with diabetes: 0.2956965223503244
For HighBP, correlation with diabetes: 0.27033413782823484
For BMI, correlation with diabetes: 0.23510351924420628
For DiffWalk, correlation with diabetes: 0.22215489287386767
For HighChol, correlation with diabetes: 0.21028966430760263
For Age, correlation with diabetes: 0.18593152591388212
For HeartDiseaseorAttack, correlation with diabetes: 0.1769333102390056
For PhysHlth, correlation with diabetes: 0.16090340865912747
For Stroke, correlation with diabetes: 0.10479969968291783
For CholCheck, correlation with diabetes: 0.06787859992199813
For Smoker, correlation with diabetes: 0.06277765755767814
For MentHlth, correlation with diabetes: 0.0453028748117598
For NoDocbcCost, correlation with diabetes: 0.03802546722845298
For Sex, correlation with diabetes: 0.029605612331244643
For AnyHealthcare, correlation with diabetes: 0.014079229503665023
For Fruits, correlation with diabetes: -0.04208771238687068
For HvyAlcoholConsump, corr

In [4]:
# Before mod
x_train0, x_test0, y_train0, y_test0 = train_test_split(df[['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']], df['Diabetes_012'], test_size = .15)
x_tr0, x_val0, y_tr0, y_val0 = train_test_split(x_train0, y_train0, test_size = .15)

In [5]:
# Balance weight full
x_train, x_test, y_train, y_test = train_test_split(df[['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']], df['Diabetes_012'], test_size = .15)
x_tr, x_val, y_tr, y_val = train_test_split(x_train, y_train, test_size = .15)


In [6]:
# Balance weight feature
x_train2, x_test2, y_train2, y_test2 = train_test_split(df[['HighBP', 'HighChol','BMI','GenHlth','DiffWalk','Age']], df['Diabetes_012'], test_size = .15)
x_tr2, x_val2, y_tr2, y_val2 = train_test_split(x_train2, y_train2, test_size = .15)


In [7]:
# Oversample full
x_train3, x_test3, y_train3, y_test3 = train_test_split(df[['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']], df['Diabetes_012'], test_size = .15)
x_tr3, x_val3, y_tr3, y_val3 = train_test_split(x_train3, y_train3, test_size = .15)

In [8]:
X = x_train3
Y = y_train3

In [9]:
#Oversample feature
x_train4, x_test4, y_train4, y_test4 = train_test_split(df[['HighBP', 'HighChol','BMI','GenHlth','DiffWalk','Age']], df['Diabetes_012'], test_size = .15)
x_tr4, x_val4, y_tr4, y_val4 = train_test_split(x_train4, y_train4, test_size = .15)


In [10]:
A = x_train4
B = y_train4

In [11]:
# undersample full
x_train5, x_test5, y_train5, y_test5 = train_test_split(df[['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']], df['Diabetes_012'], test_size = .15)
x_tr5, x_val5, y_tr5, y_val5 = train_test_split(x_train5, y_train5, test_size = .15)

In [12]:
C = x_train5
D = y_train5

In [13]:
#undersample feature
x_train6, x_test6, y_train6, y_test6 = train_test_split(df[['HighBP', 'HighChol','BMI','GenHlth','DiffWalk','Age']], df['Diabetes_012'], test_size = .15)
x_tr6, x_val6, y_tr6, y_val6 = train_test_split(x_train6, y_train6, test_size = .15)


In [14]:
E = x_train6
F = y_train6

In [15]:
# SMOTE full
x_train7, x_test7, y_train7, y_test7 = train_test_split(df[['HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education', 'Income']], df['Diabetes_012'], test_size = .15)
x_tr7, x_val7, y_tr7, y_val7 = train_test_split(x_train7, y_train7, test_size = .15)

In [16]:
G = x_train7
H = y_train7

In [17]:
# SMOTE feature
x_train8, x_test8, y_train8, y_test8 = train_test_split(df[['HighBP', 'HighChol','BMI','GenHlth','DiffWalk','Age']], df['Diabetes_012'], test_size = .15)
x_tr8, x_val8, y_tr8, y_val8 = train_test_split(x_train8, y_train8, test_size = .15)


In [18]:
I = x_train8
J = y_train8

In [19]:
# Before mod
clf0 = tree.DecisionTreeClassifier().fit(x_tr0, y_tr0)
print("Decision Tree score: %" + str(round((clf0.score(x_val0,y_val0)) * 100 , 2)))

Decision Tree score: %77.81


In [20]:
# Balance weight full
clf = tree.DecisionTreeClassifier(class_weight = "balanced").fit(x_tr, y_tr)
print("Decision Tree score: %" + str(round((clf.score(x_val,y_val)) * 100 , 2)))

Decision Tree score: %77.67


In [21]:
# Balance weight feature
clf2 = tree.DecisionTreeClassifier(class_weight = "balanced").fit(x_tr2, y_tr2)
print("Decision Tree score: %" + str(round((clf2.score(x_val2,y_val2)) * 100 , 2)))

Decision Tree score: %71.23


In [22]:
# Oversample full
ros = RandomOverSampler(random_state = 0)
x_resample, y_resample = ros.fit_resample(X,Y)
print(sorted(Counter(y_resample).items()), y_resample.shape)

[(0.0, 181617), (1.0, 181617)] (363234,)


In [23]:
# Oversample full
clf3 = tree.DecisionTreeClassifier().fit(x_resample, y_resample)
print(clf3.score(x_val3,y_val3))
print("Decision Tree score: %" + str(round((clf3.score(x_test3,y_test3)) * 100 , 2)))

0.990570412737672
Decision Tree score: %77.74


In [24]:
# Oversample feature
ros2 = RandomOverSampler(random_state = 0)
x_resample2, y_resample2 = ros2.fit_resample(A,B)
print(sorted(Counter(y_resample2).items()), y_resample2.shape)

[(0.0, 181608), (1.0, 181608)] (363216,)


In [25]:
# Oversample feature
clf4 = tree.DecisionTreeClassifier().fit(x_resample2, y_resample2)
print(clf4.score(x_val4,y_val4))
print("Decision Tree score: %" + str(round((clf4.score(x_test4,y_test4)) * 100 , 2)))

0.7432988097078373
Decision Tree score: %72.0


In [26]:
# undersample full
rus = RandomUnderSampler(random_state = 0)
x_undersample, y_undersample = rus.fit_resample(C,D)

print(sorted(Counter(y_undersample).items()), y_undersample.shape)

[(0.0, 34065), (1.0, 34065)] (68130,)


In [27]:
# Undersample full
clf5 = tree.DecisionTreeClassifier().fit(x_undersample, y_undersample)
print(clf5.score(x_val5,y_val5))
print("Decision Tree score: %" + str(round((clf5.score(x_test5,y_test5)) * 100 , 2)))

0.7652805688669037
Decision Tree score: %64.68


In [28]:
# undersample feature
rus = RandomUnderSampler(random_state = 0)
x_undersample2, y_undersample2 = rus.fit_resample(E,F)
#Checking size 
print(sorted(Counter(y_undersample2).items()), y_undersample2.shape)

[(0.0, 34010), (1.0, 34010)] (68020,)


In [29]:
# Undersample feature
clf6 = tree.DecisionTreeClassifier().fit(x_undersample2, y_undersample2)
print(clf6.score(x_val6,y_val6))
print("Decision Tree score: %" + str(round((clf6.score(x_test6,y_test6)) * 100 , 2)))

0.7428659761941567
Decision Tree score: %71.74


In [30]:
# SMOTE full
smote = SMOTE(sampling_strategy = 'minority', k_neighbors = 15)
X2, Y2 = smote.fit_resample(G,H)
Y2.value_counts()

1.0    181593
0.0    181593
Name: Diabetes_012, dtype: int64

In [31]:
# SMOTE full
clf7 = tree.DecisionTreeClassifier().fit(X2,Y2)
clf7.score(x_val7,y_val7)
print("Decision Tree score: %" + str(round((clf7.score(x_test7,y_test7)) * 100 , 2)))

Decision Tree score: %78.01


In [32]:
# SMOTE feature
smote2 = SMOTE(sampling_strategy = 'minority', k_neighbors = 15)
X3, Y3 = smote2.fit_resample(I,J)
Y3.value_counts()

0.0    181630
1.0    181630
Name: Diabetes_012, dtype: int64

In [33]:
# SMOTE feature
clf8 = tree.DecisionTreeClassifier().fit(X3,Y3)
clf8.score(x_val8,y_val8)
print("Decision Tree score: %" + str(round((clf8.score(x_test8,y_test8)) * 100 , 2)))

Decision Tree score: %76.82


In [34]:
# Before mod
y_predict0 = clf0.predict(x_test0)
print(confusion_matrix(y_test0,y_predict0))
print (y_test0.values)
print (y_predict0)

[[27620  4508]
 [ 3864  2060]]
[0. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]


In [35]:
# Balance weight full
y_predict = clf.predict(x_test)
print(confusion_matrix(y_test,y_predict))
print (y_test.values)
print (y_predict)

[[27822  4349]
 [ 3996  1885]]
[0. 1. 0. ... 1. 0. 0.]
[1. 1. 0. ... 0. 0. 1.]


In [36]:
# Balance weight feature
y_predict2 = clf2.predict(x_test2)
print(confusion_matrix(y_test2,y_predict2))
print (y_test2.values)
print (y_predict2)

[[23120  8877]
 [ 1742  4313]]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]


In [37]:
# Oversample full
y_predict3 = clf3.predict(x_test3)
print(confusion_matrix(y_test3,y_predict3))
print (y_test3.values)
print (y_predict3)

[[27707  4379]
 [ 4090  1876]]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [38]:
# Oversample feature
y_predict4 = clf4.predict(x_test4)
print(confusion_matrix(y_test4,y_predict4))
print (y_test4.values)
print (y_predict4)

[[23159  8936]
 [ 1720  4237]]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 1. ... 0. 0. 0.]


In [39]:
# Undersample full
y_predict5 = clf5.predict(x_test5)
print(confusion_matrix(y_test5,y_predict5))
print (y_test5.values)
print (y_predict5)

[[20879 11261]
 [ 2178  3734]]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [40]:
# Undersample feature
y_predict6 = clf6.predict(x_test6)
print(confusion_matrix(y_test6,y_predict6))
print (y_test6.values)
print (y_predict6)

[[23044  9041]
 [ 1711  4256]]
[0. 0. 0. ... 0. 1. 0.]
[0. 0. 0. ... 1. 0. 1.]


In [41]:
# SMOTE full
y_predict7 = clf7.predict(x_test7)
print(confusion_matrix(y_test7,y_predict7))
print (y_test7.values)
print (y_predict7)

[[27625  4485]
 [ 3884  2058]]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 1. ... 0. 0. 0.]


In [42]:
# SMOTE feature
y_predict8 = clf8.predict(x_test8)
print(confusion_matrix(y_test8,y_predict8))
print (y_test8.values)
print (y_predict8)

[[25864  6209]
 [ 2610  3369]]
[0. 0. 0. ... 0. 1. 0.]
[0. 0. 0. ... 1. 0. 1.]


In [43]:
# Before mod
print(classification_report(y_test0, y_predict0))

              precision    recall  f1-score   support

         0.0       0.88      0.86      0.87     32128
         1.0       0.31      0.35      0.33      5924

    accuracy                           0.78     38052
   macro avg       0.60      0.60      0.60     38052
weighted avg       0.79      0.78      0.78     38052



In [44]:
# Balance weight full
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       0.87      0.86      0.87     32171
         1.0       0.30      0.32      0.31      5881

    accuracy                           0.78     38052
   macro avg       0.59      0.59      0.59     38052
weighted avg       0.79      0.78      0.78     38052



In [45]:
# Balance weight feature
print(classification_report(y_test2, y_predict2))

              precision    recall  f1-score   support

         0.0       0.93      0.72      0.81     31997
         1.0       0.33      0.71      0.45      6055

    accuracy                           0.72     38052
   macro avg       0.63      0.72      0.63     38052
weighted avg       0.83      0.72      0.76     38052



In [46]:
# Oversample full
print(classification_report(y_test3, y_predict3))

              precision    recall  f1-score   support

         0.0       0.87      0.86      0.87     32086
         1.0       0.30      0.31      0.31      5966

    accuracy                           0.78     38052
   macro avg       0.59      0.59      0.59     38052
weighted avg       0.78      0.78      0.78     38052



In [47]:
# Oversample feature
print(classification_report(y_test4, y_predict4))

              precision    recall  f1-score   support

         0.0       0.93      0.72      0.81     32095
         1.0       0.32      0.71      0.44      5957

    accuracy                           0.72     38052
   macro avg       0.63      0.72      0.63     38052
weighted avg       0.84      0.72      0.76     38052



In [48]:
# Undersample full
print(classification_report(y_test5, y_predict5))

              precision    recall  f1-score   support

         0.0       0.91      0.65      0.76     32140
         1.0       0.25      0.63      0.36      5912

    accuracy                           0.65     38052
   macro avg       0.58      0.64      0.56     38052
weighted avg       0.80      0.65      0.69     38052



In [49]:
# Undersample feature
print(classification_report(y_test6, y_predict6))

              precision    recall  f1-score   support

         0.0       0.93      0.72      0.81     32085
         1.0       0.32      0.71      0.44      5967

    accuracy                           0.72     38052
   macro avg       0.63      0.72      0.63     38052
weighted avg       0.84      0.72      0.75     38052



In [50]:
# SMOTE full
print(classification_report(y_test7, y_predict7))

              precision    recall  f1-score   support

         0.0       0.88      0.86      0.87     32110
         1.0       0.31      0.35      0.33      5942

    accuracy                           0.78     38052
   macro avg       0.60      0.60      0.60     38052
weighted avg       0.79      0.78      0.78     38052



In [51]:
# SMOTE feature
print(classification_report(y_test8, y_predict8))

              precision    recall  f1-score   support

         0.0       0.91      0.81      0.85     32073
         1.0       0.35      0.56      0.43      5979

    accuracy                           0.77     38052
   macro avg       0.63      0.68      0.64     38052
weighted avg       0.82      0.77      0.79     38052



In [52]:
# Before mod
array0 = (confusion_matrix(y_test0, y_predict0))
print ("The amount of True Positives are: " + str(array0[1][1]))
print ("The amount of True Negatives are: " + str(array0[0][0]))

The amount of True Positives are: 2060
The amount of True Negatives are: 27620


In [53]:
# Balance weight full
array = (confusion_matrix(y_test, y_predict))
print ("The amount of True Positives are: " + str(array[1][1]))
print ("The amount of True Negatives are: " + str(array[0][0]))

The amount of True Positives are: 1885
The amount of True Negatives are: 27822


In [54]:
# Balance weight feature
array2 = (confusion_matrix(y_test2, y_predict2))
print ("The amount of True Positives are: " + str(array2[1][1]))
print ("The amount of True Negatives are: " + str(array2[0][0]))

The amount of True Positives are: 4313
The amount of True Negatives are: 23120


In [55]:
# Oversample full
array3 = (confusion_matrix(y_test3, y_predict3))
print ("The amount of True Positives are: " + str(array3[1][1]))
print ("The amount of True Negatives are: " + str(array3[0][0]))

The amount of True Positives are: 1876
The amount of True Negatives are: 27707


In [56]:
# Oversample feature
array4 = (confusion_matrix(y_test4, y_predict4))
print ("The amount of True Positives are: " + str(array4[1][1]))
print ("The amount of True Negatives are: " + str(array4[0][0]))

The amount of True Positives are: 4237
The amount of True Negatives are: 23159


In [57]:
# Undersample full
array5 = (confusion_matrix(y_test5, y_predict5))
print ("The amount of True Positives are: " + str(array5[1][1]))
print ("The amount of True Negatives are: " + str(array5[0][0]))

The amount of True Positives are: 3734
The amount of True Negatives are: 20879


In [58]:
# Undersample feature
array6 = (confusion_matrix(y_test6, y_predict6))
print ("The amount of True Positives are: " + str(array6[1][1]))
print ("The amount of True Negatives are: " + str(array6[0][0]))

The amount of True Positives are: 4256
The amount of True Negatives are: 23044


In [59]:
# SMOTE full
array7 = (confusion_matrix(y_test7, y_predict7))
print ("The amount of True Positives are: " + str(array7[1][1]))
print ("The amount of True Negatives are: " + str(array7[0][0]))

The amount of True Positives are: 2058
The amount of True Negatives are: 27625


In [60]:
# SMOTE feature
array8 = (confusion_matrix(y_test8, y_predict8))
print ("The amount of True Positives are: " + str(array8[1][1]))
print ("The amount of True Negatives are: " + str(array8[0][0]))

The amount of True Positives are: 3369
The amount of True Negatives are: 25864
