In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv("diabetes_012.csv")
df['Diabetes_012'].replace({2.0:1.0}, inplace = True)

#Gathering the data 
#health_df = df[['HighBP', 'HighChol', 'BMI', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'GenHlth', 'PhysHlth', 'DiffWalk', 'Age', 'Education', 'Income', 'Diabetes_012']]

#This is the dataset with all column names
oversample_copy = df[['GenHlth', 'MentHlth', 'PhysHlth', 'Diabetes_012']]


In [35]:
#Splitting into train then test set
x_full, x_test, y_full, y_test = train_test_split(oversample_copy.drop('Diabetes_012', axis = 1), oversample_copy['Diabetes_012'], test_size = 0.15)
#Splitting into train, validation, then test
x_train, x_val, y_train, y_val = train_test_split(x_full, y_full, test_size = 0.15)


In [36]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy = 'minority', k_neighbors = 15)
X, Y = smote.fit_resample(x_train,y_train)
Y.value_counts()

0.0    154574
1.0    154574
Name: Diabetes_012, dtype: int64

In [37]:
LogReg = LogisticRegression(max_iter=1000).fit(X,Y)
#print("Logistic Regression score: %" + str(round((LogReg.score(x_test,y_test)) * 100 , 2)))

In [38]:
y_predict = LogReg.predict(x_test)
print (y_test.values)
print (y_predict)

[1. 1. 0. ... 1. 0. 0.]
[1. 1. 0. ... 1. 0. 1.]


In [39]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print("Logistic Regression score: %" + str(round((LogReg.score(x_test,y_test)) * 100 , 2)))
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))



Logistic Regression score: %63.03
[[19453 12494]
 [ 1575  4530]]
              precision    recall  f1-score   support

         0.0       0.93      0.61      0.73     31947
         1.0       0.27      0.74      0.39      6105

    accuracy                           0.63     38052
   macro avg       0.60      0.68      0.56     38052
weighted avg       0.82      0.63      0.68     38052



In [40]:
#[ True Negative False positive] 
#[ False Negative True Positive ]
array = (confusion_matrix(y_test, y_predict))
print ("The amount of True Positives are: " + str(array[1][1]))
print ("The amount of True Negatives are: " + str(array[0][0]))

The amount of True Positives are: 4530
The amount of True Negatives are: 19453
